server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: motel-backend
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: ${JWT_EXPIRATION:604800000} # 7 ngày (ms)
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:2592000000} # 30 ngày (ms)
